# Generated by Django 3.2.9 on 2021-11-17 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hometitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=300)),
            ],
            options={
                'verbose_name': 'Sarlavha asosiy sahifa',
                'verbose_name_plural': 'Sarlavha asosiy sahifa',
            },
        ),
    ]
